In [1]:
import numpy as np
import itertools
import numpy.ma as ma
import random as rnd

In [2]:
alph = {
        'a' : 1, 
        'b' : 2, 
        'c' : 3, 
        'd' : 4, 
        'e' : 5, 
        'f' : 6, 
        'g' : 7, 
        'h' : 8, 
        'i' : 9, 
        'j' : 10, 
        'k' : 11, 
        'l' : 12, 
        'm' : 13, 
        'n' : 14, 
        'o' : 15, 
        'p' : 16, 
        'q' : 17, 
        'r' : 18, 
        's' : 19, 
        't' : 20, 
        'u' : 21, 
        'v' : 22, 
        'w' : 23, 
        'x' : 24, 
        'y' : 25, 
        'z' : 26
    }

In [3]:
p1 = [0, alph['z'], alph['h'], alph['o'], alph['g']]
p2 = [alph['z'], 0, alph['o'], alph['l'], alph['v']]
p3 = [alph['h'], alph['o'], 0, alph['l'], alph['a']]
p4 = [alph['o'], alph['l'], alph['l'], 0, alph['d']]
p5 = [alph['g'], alph['v'], alph['a'], alph['d'], 0]
P = np.array([p1, p2, p3, p4, p5])

In [4]:
def greedySearch(matrix, cur_indx = 0):
    start_indx = cur_indx
    path = []
    time = 0
    for _ in range(len(matrix)): 
        row = matrix[cur_indx]
        sub_row = np.copy(row)

        for i in path:
            sub_row[i] = 0

        min_indx = np.argmin(ma.masked_where(sub_row==0, sub_row))
            
        path.append(cur_indx)
        cur_indx = min_indx
    
    path.append(start_indx)

    for i in range(len(path)-1):
        time += matrix[path[i]][path[i+1]]
    return path, time

In [5]:
print(P)
print('greedy search with matrix 5x5')
for k in range(5):
    path, time = greedySearch(P, k)
    print('start id = {}'.format(k))
    print('time = {0}'.format(time))
    print('path = {0}'.format(np.array(path)+1))
    print("-------------------")

[[ 0 26  8 15  7]
 [26  0 15 12 22]
 [ 8 15  0 12  1]
 [15 12 12  0  4]
 [ 7 22  1  4  0]]
greedy search with matrix 5x5
start id = 0
time = 58
path = [1 5 3 4 2 1]
-------------------
start id = 1
time = 51
path = [2 4 5 3 1 2]
-------------------
start id = 2
time = 51
path = [3 5 4 2 1 3]
-------------------
start id = 3
time = 51
path = [4 5 3 1 2 4]
-------------------
start id = 4
time = 58
path = [5 3 1 4 2 5]
-------------------


In [6]:
matrix_random = np.zeros((10, 10))
np.fill_diagonal(matrix_random, 34)
matrix_random.tolist()

for i in range(10):
    for j in range(10):
        if(j <= i - 1):
            matrix_random[i, j] = rnd.randint(1, 33)
            matrix_random[j, i] = matrix_random[i, j]


In [7]:
path, time = greedySearch(matrix_random, k)
print('greedy search with matrix 10x10')
print('time = {0}'.format(time))
print('path = {0}'.format(path))

greedy search with matrix 10x10
time = 82.0
path = [4, 2, 5, 7, 9, 0, 6, 1, 3, 8, 4]


In [8]:
def FullSearch(matrix):
    path = np.arange(len(matrix))
    path_variations = itertools.permutations(path)
    best_path = np.arange(len(matrix))
    best_time = 100000
    max_time = 0
    for new_path in path_variations:
        new_time = 0
        for j in range(len(new_path)):
            if j != len(new_path)-1:
                new_time += matrix[new_path[j]][new_path[j+1]]
            else:
                new_time += matrix[new_path[j]][new_path[0]]
        if new_time < best_time:
            best_time = new_time
            best_path = new_path
            best_path = np.append(best_path, new_path[0])
        
        if new_time > max_time:
            max_time = new_time
    
    return best_path, best_time, max_time


In [9]:
path, best_time, max_time = FullSearch(P)
print(P)
print('full search with matrix 5x5')
print('best time = {0}'.format(best_time))
print('max time = {}'.format(max_time))
print('best path = {0}'.format(np.array(path)+1))

[[ 0 26  8 15  7]
 [26  0 15 12 22]
 [ 8 15  0 12  1]
 [15 12 12  0  4]
 [ 7 22  1  4  0]]
full search with matrix 5x5
best time = 46
max time = 76
best path = [1 3 2 4 5 1]
